vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /upload/products
      upload_destination: '%kernel.project_dir%/public/upload/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    categories:
      uri_prefix: /upload/categories
      upload_destination: '%kernel.project_dir%/public/upload/categories'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    employees:
      uri_prefix: /upload/employees
      upload_destination: '%kernel.project_dir%/public/upload/employees'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    galleries:
      uri_prefix: /upload/galleries
      upload_destination: '%kernel.project_dir%/public/upload/galleries'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    headers:
      uri_prefix: /upload/headers
      upload_destination: '%kernel.project_dir%/public/upload/headers'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
