vich_uploader:
  db_driver: orm
  metadata:
    type: attribute

  mappings:
    products:
      uri_prefix: /upload/products
      upload_destination: '%kernel.project_dir%/public/upload/products'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
